### PR TITLE
Updated versions to 1.19.2

### PR DESCRIPTION
**Pull request by Kirderf**
new textcomponent and new TranslateableComponent is now Component.translatable

Removed UUID from textcomponents since its no longer necessary

Updated method register in GAGCommands to include CommandBuildContext

player.sendMessage is now player.sendSystemMessage

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
Thanks for the contribution! I actually already had plans to port to 1.19 (and there's already a development branch for it as well), but before then, I'd like to add the Labeling Tool item (which I currently only have local code for, but am planning to also push soon once I clean up some of the details, so I'll take a proper look afterwards ^^ Also for reference, generally speaking I try to maintain a dev and main branch, so generally speaking, PRs should target the *dev* branch so I can bunch together multiple changes per release

**Comment by Kirderf** [comment]
Hey again. Wanted to make a contribution to your 1.19 plans and set the main branch as target since you dont have a 1.19 branch pushed to github. Since 1.19.3 has some major changes in code base. I would like to help you with porting to 1.19.2 since the port from there will be easier :)

**Comment by MaxNeedsSnacks** [comment]
Sorry for the late response, I've caught COVID a while ago and am currently *still* sort of busy recovering from that ^^;

My goal with GAG right now is to finish the Labeling Tool like I promised (got someone working on the UI texture and there's some other mechanics associated with it that I want to formalise in an issue soon so I don't forget down the line, but those can be introduced after the 1.19.2 port), then hopefully cleanup / fix the publishing workflow because the changelog currently still isn't working properly, and *then* I'd probably have another look at this PR since people have been asking me about a 1.19 port ^^

**Comment by MaxNeedsSnacks** [comment]
Also yeah, 1.19.3 is gonna be yet another thing I have to decide on whether that's even worth it — I probably only want to maintain two or three versions at any given time, so I might just skip that and wait for the release of .4 first, thankfully this mod isn't too large so it should be really easy to port to that though

**Comment by MaxNeedsSnacks** [comment]
Thanks for the contribution! I used your commits as base and patched them up to work with some of my other changes ^^

**Pull request merged**
